const DB_MARTERRA = [
  {
    id: 1,
    name: 'Valles Marineris',
    descriptionLong: 'El sistema de cañones más grande del sistema solar, extendiéndose por más de 4,000 km.',
    descriptionShort: 'Cañones gigantes',
    category: 'geologico',
    price: 500000,
    stock: 5,
    mainImg: '/img/terrenos/id1-main.png',
    naturalImg: '/img/terrenos/id1-natural.png',
    capacity: 215,
    population: 3.2,
  },
  {
    id: 2,
    name: 'Olympus Mons',
    descriptionLong: 'El volcán más alto conocido en el sistema solar, con una altura de 22 km.',
    descriptionShort: 'Volcán alto',
    category: 'montañoso',
    price: 800000,
    stock: 3,
    mainImg: '/img/terrenos/id2-main.png',
    naturalImg: '/img/terrenos/id2-natural.png',
    capacity: 170,
    population: 1.288,
  },
  {
    id: 3,
    name: 'Planitia Hellas',
    descriptionLong: 'Un impacto masivo que creó una cuenca en el hemisferio sur, notable por su tamaño.',
    descriptionShort: 'Cuenca de impacto',
    category: 'crater',
    price: 450000,
    stock: 7,
    mainImg: '/img/terrenos/id3-main.png',
    naturalImg: '/img/terrenos/id3-natural.png',
    capacity: 622,
    population: 1.096,
  },
  {
    id: 4,
    name: 'Polo Norte Marciano',
    descriptionLong: 'Una región cubierta de hielo de agua y dióxido de carbono, cambiante con las estaciones.',
    descriptionShort: 'Hielo estacional',
    category: 'polar',
    price: 600000,
    stock: 4,
    mainImg: '/img/terrenos/id4-main.png',
    naturalImg: '/img/terrenos/id4-natural.png',
    capacity: 110,
    population: 1.966,
  },
  {
    id: 5,
    name: 'Acidalia Planitia',
    descriptionLong: "Una vasta llanura en el hemisferio norte de Marte, famosa por su mención en 'El Marciano'.",
    descriptionShort: 'Llanura extensa',
    category: 'plana',
    price: 300000,
    stock: 8,
    mainImg: '/img/terrenos/id5-main.png',
    naturalImg: '/img/terrenos/id5-natural.png',
    capacity: 800,
    population: 936,
  },
  {
    id: 6,
    name: 'Vista Deimos',
    descriptionLong: 'Un terreno con vistas únicas al satélite Deimos.',
    descriptionShort: 'Vistas a Deimos',
    category: 'vista',
    price: 350000,
    stock: 6,
    mainImg: '/img/terrenos/id6-main.png',
    naturalImg: '/img/terrenos/id6-natural.png',
    capacity: 360,
    population: 600,
  },
  {
    id: 7,
    name: 'Pico Fobos',
    descriptionLong: 'Cercano al satélite Fobos, ideal para observación.',
    descriptionShort: 'Cerca de Fobos',
    category: 'vista',
    price: 375000,
    stock: 5,
    mainImg: '/img/terrenos/id7-main.png',
    naturalImg: '/img/terrenos/id7-natural.png',
    capacity: 112,
    population: 8930,
  },
  {
    id: 8,
    name: 'Tharsis Tholus',
    descriptionLong: 'Un terreno en una región volcánica prominente.',
    descriptionShort: 'Región volcánica',
    category: 'montañoso',
    price: 420000,
    stock: 4,
    mainImg: '/img/terrenos/id8-main.png',
    naturalImg: '/img/terrenos/id8-natural.png',
    capacity: 652,
    population: 9888,
  },
  {
    id: 9,
    name: 'Planitia Elysium',
    descriptionLong: 'Llanuras tranquilas, ideales para asentamientos.',
    descriptionShort: 'Llanuras pacíficas',
    category: 'plana',
    price: 280000,
    stock: 10,
    mainImg: '/img/terrenos/id9-main.png',
    naturalImg: '/img/terrenos/id9-natural.png',
    capacity: 712,
    population: 255,
  },
  {
    id: 10,
    name: 'Planitia Arcadia',
    descriptionLong: 'Conocida por sus patrones de hielo subterráneo.',
    descriptionShort: 'Hielo subterráneo',
    category: 'plana',
    price: 320000,
    stock: 9,
    mainImg: '/img/terrenos/id10-main.png',
    naturalImg: '/img/terrenos/id10-natural.png',
    capacity: 367,
    population: 700,
  },
  {
    id: 11,
    name: 'Vastitas Borealis',
    descriptionLong: 'Una extensa llanura en el norte de Marte.',
    descriptionShort: 'Extensa llanura norte',
    category: 'plana',
    price: 300000,
    stock: 8,
    mainImg: '/img/terrenos/id11-main.png',
    naturalImg: '/img/terrenos/id11-natural.png',
    capacity: 966,
    population: 588,
  },
  {
    id: 12,
    name: 'Planum Meridiani',
    descriptionLong: 'Un terreno con historia de exploración de rovers.',
    descriptionShort: 'Historia de rovers',
    category: 'historico',
    price: 450000,
    stock: 7,
    mainImg: '/img/terrenos/id12-main.png',
    naturalImg: '/img/terrenos/id12-natural.png',
    capacity: 999,
    population: 9600,
  },
  {
    id: 13,
    name: 'Cráter Gale',
    descriptionLong: 'Hogar del rover Curiosity, con geología variada.',
    descriptionShort: 'Hogar de Curiosity',
    category: 'historico',
    price: 475000,
    stock: 6,
    mainImg: '/img/terrenos/id13-main.png',
    naturalImg: '/img/terrenos/id13-natural.png',
    capacity: 820,
    population: 321,
  },
  {
    id: 14,
    name: 'Planitia Utopia',
    descriptionLong: 'Lugar de aterrizaje de la misión Viking 2.',
    descriptionShort: 'Aterrizaje Viking 2',
    category: 'historico',
    price: 430000,
    stock: 5,
    mainImg: '/img/terrenos/id14-main.png',
    naturalImg: '/img/terrenos/id14-natural.png',
    capacity: 120,
    population: 100,
  },
  {
    id: 15,
    name: 'Terra Sabaea',
    descriptionLong: 'Una región con variada topografía y geología.',
    descriptionShort: 'Topografía variada',
    category: 'geologico',
    price: 400000,
    stock: 6,
    mainImg: '/img/terrenos/id15-main.png',
    naturalImg: '/img/terrenos/id15-natural.png',
    capacity: 710,
    population: 877,
  },
  {
    id: 16,
    name: 'Aeolis Mons',
    descriptionLong: 'También conocido como Mount Sharp, de gran interés científico.',
    descriptionShort: 'Interés científico',
    category: 'cientifico',
    price: 550000,
    stock: 4,
    mainImg: '/img/terrenos/id16-main.png',
    naturalImg: '/img/terrenos/id16-natural.png',
    capacity: 111,
    population: 200,
  },
  {
    id: 17,
    name: 'Noctis Labyrinthus',
    descriptionLong: 'Un sistema laberíntico de valles y cañones.',
    descriptionShort: 'Valles laberínticos',
    category: 'geologico',
    price: 600000,
    stock: 3,
    mainImg: '/img/terrenos/id17-main.png',
    naturalImg: '/img/terrenos/id17-natural.png',
    capacity: 222,
    population: 995,
  },
  {
    id: 18,
    name: 'Arabia Terra',
    descriptionLong: 'Una fascinante región con historia geológica antigua.',
    descriptionShort: 'Historia geológica',
    category: 'geologico',
    price: 350000,
    stock: 7,
    mainImg: '/img/terrenos/id18-main.png',
    naturalImg: '/img/terrenos/id18-natural.png',
    capacity: 820,
    population: 144,
  },
  {
    id: 19,
    name: 'Isidis Planitia',
    descriptionLong: 'Una de las cuencas de impacto más grandes de Marte.',
    descriptionShort: 'Gran cuenca de impacto',
    category: 'd',
    price: 480000,
    stock: 5,
    mainImg: '/img/terrenos/id19-main.png',
    naturalImg: '/img/terrenos/id19-natural.png',
    capacity: 235,
    population: 520,
  },
  {
    id: 20,
    name: 'Zephyria Planum',
    descriptionLong: 'Región marcada por vientos fuertes y formaciones únicas.',
    descriptionShort: 'Vientos y formaciones',
    category: 'geologico',
    price: 410000,
    stock: 6,
    mainImg: '/img/terrenos/id20-main.png',
    naturalImg: '/img/terrenos/id20-natural.png',
    capacity: 753,
    population: 880,
  },
];

export const pedirDatos = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(DB_MARTERRA);
    }, 2000);
  });
};

export const filterCategory = (categoryid) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(DB_MARTERRA.filter((product) => product.category === categoryid));
    }, 2000);
  });
};

export const getItem = (id) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(DB_MARTERRA.find((product) => product.id == id));
    }, 2000);
  });
};
